language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "mystocks-test";' -U postgres
script:
  - npm test # test the code
  - npm run build-client # make the bundle

before_deploy:
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: mystocks-ttp # see README
  api_key:
    secure: "igKX/uZxCV6iuZCi5zKgrVTusX3mEXQXAo5Pp7hkWti7WNzTpfN8jviUQqutHfN7eGETAEuBfJinH7HvXFfLapBmGv5dElt6OPzZ+MpEx6hlcHYJyodj4Y7B7xqeiFzNbEtPa+VY7h+HcYeVPhztExLTMz8PWOwXQSpxaygAVeFX5DKsS5EQIr/TeFM1LRjeYJToJJEOo4uSVgVFtaHoC2nO7zO1a5h1O3AcSViW4WvT/oEjcYcyS+YMzEiwqbJ0xz2BvLZ5FmUzkYyFQ5scdW7UakW1Oe2YcsUhTINIeezt9R6pU3AhKssP5cxhs12qrcGlUDR0EPHXrE2DY2xQ4qf8FGiBGKtNVph4ZhE4moczebKPl7uCr0BQvGcs/zldreTNYzv9trr0SA6sA9bpluOiGjfEFvH2y1TAZVJ96R1cseANopE0pMSvE+GvqOSSolQrAIWYqrt0/e0jSR0cxmhAbdvd1XWoy41yWZXqv5abA61RU55IH0gN+X8TTvSf7Hx/6Jm5YoRRdmCqaa9mDvzPUQhYogfRO1uvXFaQ1Nq7PXP4XSaqBfCPu9+9geCaxSzKQ60UdhVSnlCwVQaZ+gCtkDkkoszGz5bVo7yWgJ+XntCcNGNvJ3nrnHXhi8BPKsIjI3IBjBkavF17M2bpFIHYA2FmF+jcTFcrWsMol+U="
